import { Document, Page, Text, View } from "@react-pdf/renderer";
import type { SummaryBlock } from "@/lib/summary-markdown";
import { styles } from "./helpers/styles";
import BlockSegments from "./components/block-segments";

interface Props {
  lessonTitle: string;
  meta: string;
  generatedOn: string;
  blocks: SummaryBlock[];
}

const SummaryDocument = ({ lessonTitle, meta, generatedOn, blocks }: Props) => (
  <Document title={`Lesson summary — ${lessonTitle}`}>
    <Page size="A4" style={styles.page}>
      <View style={styles.bar} fixed>
        <Text style={styles.wordmark}>Educatio</Text>
      </View>

      <Text style={styles.title}>Lesson Summary</Text>

      <View style={styles.meta}>
        <Text style={styles.metaTitle}>{lessonTitle}</Text>
        {meta.length > 0 && <Text style={styles.metaLine}>{meta}</Text>}
      </View>

      <View style={styles.divider} />

      {blocks.map((block, index) => {
        if (block.kind === "heading") {
          return (
            <Text key={index} style={styles.heading}>
              <BlockSegments block={block} />
            </Text>
          );
        }
        if (block.kind === "paragraph") {
          return (
            <Text key={index} style={styles.paragraph}>
              <BlockSegments block={block} />
            </Text>
          );
        }
        return (
          <View key={index} style={styles.row}>
            <Text style={styles.marker}>
              {block.kind === "numbered" ? block.marker : "•"}
            </Text>
            <Text style={styles.rowBody}>
              <BlockSegments block={block} />
            </Text>
          </View>
        );
      })}

      <Text style={styles.footer} fixed>
        {`Generated by Educatio · ${generatedOn}`}
      </Text>
    </Page>
  </Document>
);

export default SummaryDocument;
