import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";
import type { SummaryBlock } from "@/lib/summary-markdown";

const INK = "#1c1917";
const MUTED = "#57534e";
const ACCENT = "#4338ca";
const TINT = "#f5f5f4";
const RULE = "#e7e5e4";

const styles = StyleSheet.create({
  page: {
    paddingTop: 68,
    paddingBottom: 56,
    paddingHorizontal: 40,
    fontFamily: "Helvetica",
    fontSize: 10.5,
    color: INK,
    lineHeight: 1.5,
  },
  bar: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: 40,
    backgroundColor: ACCENT,
    justifyContent: "center",
    paddingHorizontal: 40,
  },
  wordmark: { color: "#ffffff", fontSize: 12, fontFamily: "Helvetica-Bold" },
  title: { fontSize: 20, fontFamily: "Helvetica-Bold", marginBottom: 12 },
  meta: { backgroundColor: TINT, padding: 12, borderRadius: 4 },
  metaTitle: { fontSize: 11, fontFamily: "Helvetica-Bold" },
  metaLine: { fontSize: 9.5, color: MUTED, marginTop: 3 },
  divider: {
    borderBottomWidth: 1,
    borderBottomColor: RULE,
    marginTop: 16,
    marginBottom: 14,
  },
  heading: {
    fontSize: 12,
    fontFamily: "Helvetica-Bold",
    color: ACCENT,
    marginTop: 14,
    marginBottom: 5,
  },
  paragraph: { marginBottom: 6 },
  row: { flexDirection: "row", marginBottom: 4 },
  marker: { width: 16, color: MUTED },
  rowBody: { flex: 1 },
  bold: { fontFamily: "Helvetica-Bold" },
  footer: {
    position: "absolute",
    bottom: 24,
    left: 40,
    right: 40,
    fontSize: 8.5,
    color: ACCENT,
  },
});

interface Props {
  lessonTitle: string;
  meta: string;
  generatedOn: string;
  blocks: SummaryBlock[];
}

const Inline = ({ block }: { block: SummaryBlock }) => (
  <>
    {block.segments.map((segment, index) => (
      <Text key={index} style={segment.bold ? styles.bold : undefined}>
        {segment.text}
      </Text>
    ))}
  </>
);

const SummaryDocument = ({ lessonTitle, meta, generatedOn, blocks }: Props) => (
  <Document title={`Lesson summary — ${lessonTitle}`}>
    <Page size="A4" style={styles.page}>
      <View style={styles.bar} fixed>
        <Text style={styles.wordmark}>Educatio</Text>
      </View>

      <Text style={styles.title}>Lesson Summary</Text>

      <View style={styles.meta}>
        <Text style={styles.metaTitle}>{lessonTitle}</Text>
        {meta.length > 0 && <Text style={styles.metaLine}>{meta}</Text>}
      </View>

      <View style={styles.divider} />

      {blocks.map((block, index) => {
        if (block.kind === "heading") {
          return (
            <Text key={index} style={styles.heading}>
              <Inline block={block} />
            </Text>
          );
        }
        if (block.kind === "paragraph") {
          return (
            <Text key={index} style={styles.paragraph}>
              <Inline block={block} />
            </Text>
          );
        }
        return (
          <View key={index} style={styles.row}>
            <Text style={styles.marker}>
              {block.kind === "numbered" ? block.marker : "•"}
            </Text>
            <Text style={styles.rowBody}>
              <Inline block={block} />
            </Text>
          </View>
        );
      })}

      <Text style={styles.footer} fixed>
        {`Generated by Educatio · ${generatedOn}`}
      </Text>
    </Page>
  </Document>
);

export default SummaryDocument;
